### PR TITLE
WIP: An attempt to cleanup query resource. Part of STCOR-134

### PR DESCRIPTION
**Pull request by mkuklis**
This is still a WIP so please don't merge it.

### CODE REVIEW

**Comment by mkuklis** [comment]
@zburke I moved couple things around here. Would you mind giving it a try? Let's continue our discussion tomorrow morning.

**Comment by MikeTaylor** [comment]
It's really nice to see this code starting to look so much more comprehensible.

Does the present version fix any of the bugs yet?

**Comment by zburke** [comment]
So far, I can confirm it fixes [STSMACOM-50](https://issues.folio.org/browse/STSMACOM-50), [UISE-57](https://issues.folio.org/browse/UISE-57), [UIU-384](https://issues.folio.org/browse/UIU-384), and the halting problem.

**Comment by zburke** [comment]
Unfortunately, [UISE-56](https://issues.folio.org/browse/UISE-56) is now _more_ broken: after clicking a local-inventory record from the results list in ui-search, the back-button is now completely broken.

**Comment by mkuklis** [comment]
Thank you both for testing this! Zak maybe we can look at what is going on with UISE-56 today?

**Pull request merged**
