### PR TITLE
Add an Apollo provider configured for the mod-graphql endpoint

### PR DESCRIPTION
**Pull request by skomorokh**
Apollo is a GraphQL client. This lets you use it in Stripes. Specifically, it adds a component to provide Apollo's React binding with the necessary context to send queries to mod-graphql, the Okapi endpoint for resolving them.

### CODE REVIEW

**Comment by MikeTaylor** [comment]
"lets", not "let's" :-)

**Comment by MikeTaylor** [comment]
That aside -- go ahead, merge!

**Comment by MikeTaylor** [comment]
Do it!

**Comment by skomorokh** [comment]
Thanks, ya, I dunno, sometime in the past decade I just unconsciously see homonyms as interchangeable whereas before it'd have been glaring to me. Neuroplasticity is weird.

**Pull request merged**
