### PR TITLE
STCOR-524: Updated app context menu button style

### PR DESCRIPTION
**Pull request by rasmuswoelk**
## Ticket
https://issues.folio.org/browse/STCOR-524

## Changes
- Extracted home button into a `<CurrentAppButton>` component and used this component for both the home button and the app context dropdown trigger button
- Added an 'open'-prop for the <NavButton> that renders a caret icon
- Fixed app context dropdown implementation so that it closes on outside click

## Before
image

## After
image

### CODE REVIEW

**Review by zburke — CHANGES_REQUESTED** [review]
The style changes look great ... but clicking the ui-users app's "Keyboard shortcuts" menu item no longer triggers that modal.

**Comment by rasmuswoelk** [comment]
> The style changes look great ... but clicking the ui-users app's "Keyboard shortcuts" menu item no longer triggers that modal.

I can't believe I missed that.. I pushed a commit that fixes that issue.

**Review by zburke — APPROVED** [review]
LGTM now, but the new code here is uncovered by tests.

**Comment by rasmuswoelk** [comment]
> LGTM now, but the new code here is uncovered by tests.

Thanks – I'll add tests and merge it in 👍

**Pull request merged**
