### PR TITLE
STCOR-640: Add `button.duplicate` translation key

### PR DESCRIPTION
**Pull request by ncovercash**
# [Jira](https://issues.folio.org/projects/STCOR/issues/STCOR-640)

This is consistent with the UX pattern, as described [here](https://ux.folio.org/docs/guidelines/ux-patterns/duplicate-a-record/).  Adds a centralized duplicate button key to prevent modules having to provide separate translations for this common use. 

_Je parle un peu français_, so I added translations for fr and fr_FR.

### CODE REVIEW

**Comment by zburke** [comment]
@ncovercash, what's the goal here, just to get "Duplicate" into one central place so that ui-whatever can (should) use `<FormattedMessage id="stripes-core.button.duplicate" />` instead of having `id="ui-whatever.duplicate"` keys spread across multiple repos? That's fine if so. I just want to make sure I understand :) Even when there is a verbose Jira description, it's still helpful to include a one-liner in the GitHub PR to briefly explain the "why" in addition to the subject-line's "what". 

NB: values for anything outside `en.js` are handled through a separate process so any changes committed here will be overwritten. There is nothing wrong with adding them, but the data flow is one-way from `en.json` out to Lokalise.co, and then one-way back in from Lokalise to the various locale.json files so it's wasted effort.

**Review by zburke — APPROVED** [review]

**Comment by ncovercash** [comment]
@zburke that's the goal, sorry for the gap in communication.  Didn't know about that for lokalise (that process is a bit of a mystery to me, admittedly) - will keep that in mind for the future

**Comment by zburke** [comment]
@ncovercash If you can update this branch I'm happy to merge the PR.

**Comment by ncovercash** [comment]
@zburke done

**Pull request merged**
