### PR TITLE
subscribe to query when module location changes

### PR DESCRIPTION
**Pull request by wwelling**
resolves [UIU-357](https://issues.folio.org/browse/UIU-357)

### CODE REVIEW

**Comment by zburke** [comment]
I'm seeing weird jitter in the URL after this update. 

url_jitter

**Comment by wwelling** [comment]
@zburke I am unable to reproduce what you are showing. Could you list steps to reproduce?

**Comment by wwelling** [comment]
Seems to work as expected here http://folio-testing.aws.indexdata.com

**Comment by zburke** [comment]
Argh; false alarm. There must've been something corrupt in my build. The problem persisted through a browser restart, but cleared up after rebuilding the bundle. Sorry for the hassle.

**Comment by wwelling** [comment]
No worries. Gave me a chance to take another look at the code and discovered I can prevent unsubscribing and subscribing superfluously.

**Comment by zburke** [comment]
Oddly, I am seeing this behavior on http://folio-testing.aws.indexdata.com now, though I did not last night. I'm also seeing URL query values wrongly carried over across applications, e.g. if I click "inventory" and then "settings", I can sometimes get a URL like 
    http://folio-testing.aws.indexdata.com/settings?filters=&query=&sort=-title%2C-contributors
which should not have that querystring. Curiouser and curiouser.

**Comment by wwelling** [comment]
I think I know what is happening. Will update in about 30-45 minutes.

**Comment by wwelling** [comment]
@zburke thanks for testing and discovering this. It was due to having multiple subscriptions to URL query changes. It is resolved here: https://github.com/folio-org/stripes-core/pull/146

**Pull request merged**
