### PR TITLE
STRIPES-749 Pass tenant info when making saml login call

### PR DESCRIPTION
**Pull request by hjiebsco**
Minor change. Please see https://issues.folio.org/browse/STRIPES-749 Pass tenant info when making saml login call. BTW this one is based on the same branch for STRIPES-683, so it includes the change of https://github.com/folio-org/stripes-core/pull/1067 as well.

### CODE REVIEW

**Review by zburke — APPROVED** [review]
I hijacked this PR a bit. Sorry!

I added a comment to explain the change, and also added `login-saml` to `optionalOkapiDependencies`. Really, we should have this code blocked off by `<IfInterface>` checks, but at least including the dep is a good start. I can't believe we didn't notice this earlier! 😬 If you are happy with the changes, feel free to merge. If not, feel free to scream at me for hijacking your PR and I can revert the commit. 

Was it your intention to open this PR against the `b7.1` branch, i.e. it will become a patch release for Iris? Should we open the same PR against the master branch so it will be part of Juniper?

**Comment by hjiebsco** [comment]
> I hijacked this PR a bit. Sorry!
> 
> I added a comment to explain the change, and also added `login-saml` to `optionalOkapiDependencies`. Really, we should have this code blocked off by `<IfInterface>` checks, but at least including the dep is a good start. I can't believe we didn't notice this earlier! 😬 If you are happy with the changes, feel free to merge. If not, feel free to scream at me for hijacking your PR and I can revert the commit.
> 
> Was it your intention to open this PR against the `b7.1` branch, i.e. it will become a patch release for Iris? Should we open the same PR against the master branch so it will be part of Juniper?

Thank you @zburke. Should we create/update PR to merge into master? Or merge to `b7.1` and then cherry pick it to merge to master?

**Review by mkuklis — APPROVED** [review]

**Comment by hjiebsco** [comment]
@zburke and @mkuklis, thanks for approving the PR. I changed the base branch to master since it was not meant to be a patch release. Now "Some checks were not successful", could you take a look? Thanks.

**Comment by zburke** [comment]
@hjiebsco, the "buildNPM Snapshot" failures appear unrelated to the actual code changes here. That's a new pipeline devops has configured as an alternative to Jenkins and I guess there are still some kinks to work out. The jenkins builds on this PR look good to me.

**Review by zburke — APPROVED** [review]

**Pull request merged**
