### PR TITLE
Explicitly declare UTF-8 character encoding

### PR DESCRIPTION
**Pull request by cherewaty**
Resolves https://issues.folio.org/browse/UIEH-24

### CODE REVIEW

**Comment by MikeTaylor** [comment]
it looks like I am not only not allowed to merge this obviously correct, PR, I am not even allowed to submit a review that will allow _you_ to merge it. Anyway, here is my impotent, non-operative review, in the form of a comment: this PR is fine.

**Comment by cowboyd** [comment]
github medic!

**Comment by zburke** [comment]
@MikeTaylor I figured out you can approve a PR you haven't been assigned to review by clicking the "Files changed" tab; it has a green "Review changes" button/menu at top right. I haven't decided if this is a bug (maybe only assigned reviewers are supposed to be able to approve PRs?) or an undocumented feature.

**Comment by MikeTaylor** [comment]
Hmm. Well, nice detective work. Thanks, @zburke.

**Pull request merged**
